# Generated by Django 6.0.6 on 2026-06-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAdmin',
            fields=[
                ('clinic_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('clinic_name', models.CharField(max_length=100)),
                ('clinic_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('department_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_mob_number', models.CharField(max_length=10)),
                ('status', models.CharField(default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_mob_number', models.CharField(max_length=10)),
                ('status', models.CharField(default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_mob_number', models.CharField(max_length=10)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='Active')),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinicadmin')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nurse_name', models.CharField(max_length=100)),
                ('nurse_email', models.EmailField(max_length=254)),
                ('nurse_mob_number', models.CharField(max_length=10)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Active')),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinicadmin')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
        ),
    ]
