# Generated by Django 6.0.6 on 2026-06-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicadmin',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2002-05-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2002-05-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2002-05-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2002-05-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2002-05-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2002-05-06'),
            preserve_default=False,
        ),
    ]
